### ISSUE TITLE
请问这个和wafer-client-sdk 到底有什么区别？

### ISSUE THREAD

**Issue by codermango** [tencentyun/wafer2-client-sdk#1]
https://github.com/tencentyun/wafer-client-sdk
不好意思我实在是被你们提供的各种repo里的东西搞的晕头转向，比如这个wafer2和wafer到底有什么区别。

**Comment by jas0ncn** [comment]
wafer2-client-sdk 是搭配新版的小程序解决方案使用的哈。你如果是使用旧版的小程序解决方案，就是用wafer-client-sdk 哈
![cd5d5824-7a1b-4ad7-9dbe-b47dbf42fe91](https://user-images.githubusercontent.com/3380894/29996263-28988940-902e-11e7-8fa6-9389c268d823.png)

**Comment by codermango** [comment]
谢谢谢谢 👍
