### ISSUE TITLE
小程序初次进入时，接口登录问题

### ISSUE THREAD

**Issue by wjryours** [tencentyun/wafer2-client-sdk#10]
假如我初次进入一个小程序页面，同时调用2个接口，这2个接口都需要登录才能获取信息，这时候调用login中的`getLoginCode()`方法时只会触发一次`wx.getUserInfo()`函数，这样回调只会响应2个接口中的一个接口，这样即使授权成功，还是会有一个接口无法取得数据，不知道我这个说的明白没有，

**Comment by jas0ncn** [comment]
调用接口之前需要先判断登录态哈~
