### ISSUE TITLE
调用 login 无法传参

### ISSUE THREAD

**Issue by byk04712** [tencentyun/wafer2-client-sdk#14]
查看代码  [login.js](https://github.com/tencentyun/wafer2-client-sdk/blob/master/lib/login.js#L28-L43) 中，无法传入小程序文档中的参数，如 `withCredentials` , `lang`, 等

**Comment by jas0ncn** [comment]
已修改支持，感谢提醒！
https://github.com/tencentyun/wafer2-client-sdk/commit/d7dd282acbe611f0d7cf30b2ca65d851aef20495
