### ISSUE TITLE
 qcloud.login返回数据没有openid了吗？是错误还是特意？

### ISSUE THREAD

**Issue by JiaXinYi** [tencentyun/wafer2-client-sdk#15]
qcloud.login({
      success(result) {
        if (result) {
//why no openId anymore？
}

thank you so much

**Comment by jas0ncn** [comment]
有 openid 的

**Comment by JiaXinYi** [comment]
![image](https://user-images.githubusercontent.com/18085971/37864542-a14870f4-2fab-11e8-87ec-c205f78f1a6a.png)
@jas0ncn 
首次登陆这里，没有的，我输出来了，前几天用的时候是有的

**Comment by jas0ncn** [comment]
这里是透传微信的 wx.getUserinfo 接口，目前看了一下官方的文档，似乎是去掉了 openid 字段，你可以手动在登录之后请求一下后台的 /user 接口，返回的信息中是完整的。

**Comment by JiaXinYi** [comment]
已实现，感谢
