### ISSUE TITLE
希望尽快适配wx.getUserInfo的接口废弃

### ISSUE THREAD

**Issue by Titansonia** [tencentyun/wafer2-client-sdk#17]
参考链接
https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=1650183953&docid=0000a26e1aca6012e896a517556c01

**Comment by sumshare** [comment]
目前我的方案是按照API文档给的demo加了个检测页面，wx.getSetting检测授权。嗯，demo贼不走心

**Comment by caidows** [comment]
来顶一下 请尽快实现前后端sdk

**Comment by vanCopper** [comment]
来顶一下，希望能把登陆，和获取用户信息分开来

**Comment by zhu512** [comment]
感谢各位，已做wx.getUserInfo适配。
