### ISSUE TITLE
新的接口requestLogin返回错误

### ISSUE THREAD

**Issue by langwan** [tencentyun/wafer2-client-sdk#23]
> qcloud.requestLogin({
          loginParams

这个loginParams里面只有code 返回这个错误

LoginError {type: "ERR_LOGIN_MISSING_SESSION", message: "{"message":"Illegal Buffer"}"}

**Comment by langwan** [comment]
> Error: Invalid IV length
    at new Decipheriv (internal/crypto/cipher.js:186:16)

**Comment by langwan** [comment]
encryptedData, iv 从哪里来的？

**Comment by jas0ncn** [comment]
已经修正，感谢提醒！
