### ISSUE TITLE
配合wafer2-node-sdk，调用requestLogin，并不会将用户信息存到csessionInfo中

### ISSUE THREAD

**Issue by xinconan** [tencentyun/wafer2-client-sdk#26]
配合wafer2-node-sdk，调用requestLogin方法，并不会将用户信息存到csessionInfo中。login 方法就可以，要怎么样才能保存到数据库中？

**Comment by jas0ncn** [comment]
参考一下调用示例哈：https://github.com/tencentyun/wafer2-client-sdk/blob/master/README.md#%E7%99%BB%E5%BD%95
如果还是不行，能否提供一下报错信息呢？

**Comment by xinconan** [comment]
本地启动成功入库，部署到线上就登录不了

**Comment by jas0ncn** [comment]
你是自行部署还是用的 wafer 方案呢？具体的报错信息是什么呢？

**Comment by xinconan** [comment]
这个问题解决了，因为线上使用了端口映射转发，少加了路由前缀
