### ISSUE TITLE
关于自动登录的疑问

### ISSUE THREAD

**Issue by langwan** [tencentyun/wafer2-client-sdk#28]
在接口调整之前，在调用api的时候传入login:true参数会在需要的时候直接弹出授权，授权成功会继续执行所需要的接口，但是在接口调整之后这个参数好像不管用了。

> qcloud.setLoginUrl('https://199447.qcloud.la/login');
qcloud.request({
    login: true,
    url: 'http://199447.qcloud.la/user',
    success: function (response) {
        console.log(response);
    },
    fail: function (err) {
        console.log(err);
    }
});

是否意味着官方文档需要修改了，这个参数作废了，如果作废了，对应的解决方案是什么？

现在使用button进行弹出，实际上需要sdk给我进行回调，我在回调里弹出我自己的auth页面，我的理解是这样，是否存在这样的回调可以用，还是有其它的解决方法

**Comment by langwan** [comment]
如果作废了，对应的解决方案是什么？

**Comment by jas0ncn** [comment]
已经更新了新版本，请查看文档：https://github.com/tencentyun/wafer2-client-sdk#%E7%99%BB%E5%BD%95
