### ISSUE TITLE
两个问题

### ISSUE THREAD

**Issue by joe915** [tencentyun/wafer2-client-sdk#34]
1.qcloud.requestLogin  这个函数在案例 和 源码中都没有找到 
2.源码中的登录 还是 和 获取用户信息绑定在一起的，能分开么

**Comment by jas0ncn** [comment]
requestLogin 已经改名为 login，只想要登录可以调用 loginWithCode 这个 API。具体查看：https://github.com/tencentyun/wafer2-quickstart/issues/10
