### ISSUE TITLE
TypeError: Cannot read property 'skey' of null

### ISSUE THREAD

**Issue by qiuzx20** [tencentyun/wafer2-client-sdk#35]
TypeError: Cannot read property 'skey' of null
    at doRequest (http://127.0.0.1:24444/appservice/vendor/wafer2-client-sdk/lib/request.js:79:55)

Session.get() 为null
请问一下，微信小程序开发时，这个问题需要怎么解决？

**Comment by jas0ncn** [comment]
什么版本的？可以更新一下最新版看看

**Comment by qiuzx20** [comment]
更新后已没报错了，thx
