### ISSUE TITLE
sdk内部getWxLoginResult调用了wx.getUserInfo一直报错

### ISSUE THREAD

**Issue by yhongm** [tencentyun/wafer2-client-sdk#38]
我是通过button opentype方式调用的登录，结果你们sdk内部调用了getUserInfo这个方法
VM4650:1 获取 wx.getUserInfo 接口后续将不再出现授权弹窗，请注意升级。
你们微信废弃了，不让外面用，你们sdk内部调用的时候还调用这个方法？？？
为什么你们sdk内部调用微信开发工具还是提示wx.getUserInfo 接口后续将不再出现授权弹窗，请注意升级。再说我也不是进入小程序时候调用的？？[](url)

**Comment by yhongm** [comment]
为什么qcloud.Session.get()找不到get??

**Comment by yhongm** [comment]
为什么你们sdk内部调用的getUserInfo还是提示这个？？
![_20180705155714](https://user-images.githubusercontent.com/3638074/42309815-4bd3c22e-806c-11e8-89bb-33e0a7ddaa0a.png)

**Comment by jas0ncn** [comment]
这个提示是只要调用了 getUserInfo 就会提示，就算是正确调用也会。
