### ISSUE TITLE
登录态已过期

### ISSUE THREAD

**Issue by yuzifu** [tencentyun/wafer2-client-sdk#4]
有两个类似的request，代码如下：
`
var host = 'localhost:5757';
var config = {
    // 下面的地址配合云端 Demo 工作
    service: {
        host,
        // 登录地址，用于建立会话
        loginUrl: `http://${host}/weapp/login`,
        payUrl: `http://${host}/weapp/pay`,
        doorUrl: `http://${host}/weapp/door`,
    }
};

function doorRequest (doorid) {
    if (doorid) {
        var currDate = new Date().Format('yyyyMMddhhmmss');
        qcloud.request({
            login: true,
            url: config.service.doorUrl,
            data: { item: '[' + doorid + ']@[' + currDate + ']' },
            method: 'POST',
            header: {
                'content-type': 'application/json'
            },
            success: function (res) {
                if ('code' in res.data && res.data.code >= 0) {
                    console.log('door request success,', res);
                } else {
                    console.log('process door request fail,', res.data);
                }
            },
            fail: function (res) {
                console.log('door request fail,', res);
            }
        });
    }
}

function payRequest (payinfo) {
    var that = this;
    var arrpay = payinfo.split(',')
    if (arrpay.length == 3) {
        qcloud.request({
            login: true,
            url: config.service.payUrl,
            data: { item: payinfo },
            method: 'POST',
            header: {
                'content-type': 'application/json'
            },
            success: function (res) {
                if ('code' in res.data && res.data.code >= 0) {
                    console.log('success', res);
                } else {
                    console.log(res.data.msg);
                }
            },
            fail: function (res) {
                console.log('pay request fail,', res);
            }
        });
    }
}`

调用doorRequest进行请求的时候都能成功，但是调用payRequest进行请求的时候却重复4次后显示『登录态已过期』，尝试过交叉调用它们俩，结果是一样的，很怪异的事情。

**Comment by jas0ncn** [comment]
这个主要是看你 `/pay` 是怎么实现的

**Comment by yuzifu** [comment]
router.post('/pay', validationMiddleware, controllers.pay)

module.exports = async (ctx, next) => {
ctx.body = {
code: -1,
msg: 'fail'
}
}

**Comment by jas0ncn** [comment]
你使用的是什么版本的客户端 demo 呢？

**Comment by yuzifu** [comment]
2.0.2

**Comment by jas0ncn** [comment]
2.0.2？方便提供一下下载地址吗？

**Comment by yuzifu** [comment]
https://github.com/tencentyun/wafer2-startup/releases

**Comment by yuzifu** [comment]
自定义的业务返回对象名称被SDK返回对象使用了？那有哪些关健字是被SDK使用了的？
一开始我是准备把业务返回对象存储是ctx.state.data的，比如: ctx.state.data = { code: 0, msg: 'ok', data: 'request success' }，但发现客户端接收到的返回对象只有code和msg两个值，data值不存在。
你们建议业务返回对象放在哪更适合？
