### ISSUE TITLE
wx.uploadFile请求无法传x-wx-key这个header信息

### ISSUE THREAD

**Issue by dennis-ji** [tencentyun/wafer2-client-sdk#40]
如果使用qcloud.request的话，可以正常传x-wx-key这个header用于登录验证，
但是，
wx.uploadFile请求无法传x-wx-key这个header信息。
如何解决？

**Comment by jas0ncn** [comment]
可以仿照 request 从 Session 中取 skey：https://github.com/tencentyun/wafer2-client-sdk/blob/master/lib/request.js#L77
