### ISSUE TITLE
接口测试没有一个成功

### ISSUE THREAD

**Issue by z8751300** [tencentyun/wafer2-client-sdk#41]
LoginError {type: "ERR_LOGIN_MISSING_SESSION", message: "登录请求没有包含会话响应，请确保服务器处理 `http://localhost:5757/weapp/login` 的时候正确使用了 SDK 输出登录结果"}

**Comment by jas0ncn** [comment]
参考 DEMO 的调用方式哈：https://github.com/tencentyun/wafer2-quickstart-nodejs
