### ISSUE TITLE
挖坑

### ISSUE THREAD

**Issue by z8751300** [tencentyun/wafer2-client-sdk#43]
VM1717:1 Error: 响应错误，{"code":-1,"error":"ERR_WHEN_INSERT_TO_DB\nError: ER_ACCESS_DENIED_ERROR: Access denied for user 'root'@'localhost' (using password: NO)"}

**Comment by jas0ncn** [comment]
你好，这是由于你的数据库密码不是小程序的 APPID 导致的，请检查一下你的密码~
