### ISSUE TITLE
qcloud.request无法发送data?

### ISSUE THREAD

**Issue by wbpmrck** [tencentyun/wafer2-client-sdk#46]
API里为什么不预留data字段？这样业务接口只能使用header传信息了。

**Comment by jas0ncn** [comment]
有 data 字段，可以使用 data 字段发送请求。参数基本和 `wx.request` 是一样的哈

**Comment by MaxPoon** [comment]
@jas0ncn request.js中使用`wx.request`时并没有用到data字段
