### ISSUE TITLE
信道一直收到服务器返回的“数字”响应？

### ISSUE THREAD

**Issue by whombu** [tencentyun/wafer2-client-sdk#49]
{data: "0"}
{data: "1"}
{data: "2"}
{data: "3"}
{data: "server get message: ping"} 
{data: "4"} 
{data: "5"} 
{data: "6"} 
{data: "7"} 
{data: "8"}
然后就启动超时重连了（因为没有收到PONG）
我的信道服务配置的是ws.qcloud.com

**Comment by jas0ncn** [comment]
要连接 tunnel.qcloud.la 哈~

**Comment by whombu** [comment]
请问一下，是在sdk.config配置文件中配置https://tunnel.qcloud.la么，在开发设置里配置这个URL，提示只可以在开发环境中使用。

**Comment by whombu** [comment]
https://tunnel.qcloud.la/
报异常UnknownHostException

**Comment by jas0ncn** [comment]
不好意思，写错了，是 http://tunnel.ws.qcloud.la

**Comment by whombu** [comment]
> 不好意思，写错了，是 http://tunnel.ws.qcloud.la

可以用了，感谢感谢!
