### ISSUE TITLE
获取用户信息失败

### ISSUE THREAD

**Issue by zhenghaotc** [tencentyun/wafer2-client-sdk#51]
{\"errcode\":40013,\"errmsg\":\"invalid appid, hints: [ req_id: IgXGma08222015 ]\"}"}

**Comment by jas0ncn** [comment]
如提示所说的 appid 是无效的，填的是微信小程序的 appid 吗？

**Comment by zhenghaotc** [comment]
> 如提示所说的 appid 是无效的，填的是微信小程序的 appid 吗？

填的是小程序的appid

**Comment by jas0ncn** [comment]
应该是填错了，确认一下 appid 有没有空格啥的
