### ISSUE TITLE
10月10号后 wx.getUserInfo接口被微信回收，该怎么处理？ 

### ISSUE THREAD

**Issue by neil-pan-s** [tencentyun/wafer2-client-sdk#54]
login.js 中仍旧用的是 wx.getUserInfo， 是不是要更新这个库？

**Comment by jas0ncn** [comment]
`wx.getUserInfo` 只是**不再弹窗**，而不是**无法使用**。请配合 README.md 进行更改：https://github.com/tencentyun/wafer2-client-sdk#%E7%99%BB%E5%BD%95

**Comment by sunchangmei123** [comment]
现在改成了getUsetProfile,这可咋办呢（哭~~~）
