### ISSUE TITLE
session 里面都没有存 userinfo的 值，这个里面返回个鬼哦....  

### ISSUE THREAD

**Issue by moyuanhua** [tencentyun/wafer2-client-sdk#8]
https://github.com/tencentyun/wafer2-client-sdk/blob/dada27c06176721656a7ddcfc4c98965b9255e11/lib/login.js#L139

**Comment by jas0ncn** [comment]
这里是个已知问题。因为 SDK 是从 1.0 迁移的，2.0 直接存储了 skey 在 Session 中，不再存储 userInfo 的。本意是为了每次登录都去更新一下 userinfo，以保证用户信息的最新（昵称、头像等）。
