### ISSUE TITLE
建议将登录和获取用户信息的逻辑区分开

### ISSUE THREAD

**Issue by XiaoChenYung** [tencentyun/wafer2-client-sdk#9]
https://github.com/tencentyun/wafer2-startup/issues/21
就是这个问题，可否解决，把逻辑分开，如果可以解决可都给出一个时间表

**Comment by jas0ncn** [comment]
可能没有那么快可以解决哈

**Comment by XiaoChenYung** [comment]
那算了，我们自己实现吧🤣

**Comment by youlangu** [comment]
自己的方案描述的场景的多好，但是就是SDK自己不支持，这么长时间了还是没见解决，这脸打的啪啪响

[获取用户信息方案介绍](https://developers.weixin.qq.com/blogdetail?action=get_post_info&lang=zh_CN&token=&docid=c45683ebfa39ce8fe71def0631fad26b)

**Comment by youlangu** [comment]
小程序建议的登录流程是，通过 wx.login 获取用户 openID, 这时无需弹框授权，开发者拿到 openID 可以建立自身的帐号 ID。当必须要获得用户的头像昵称等信息时，才让用户点击 button（open-type="getUserInfo" ），弹框授权。

**Comment by jas0ncn** [comment]
是的，感谢再次提醒，这个我们最近开始调研实现这个功能，大概两周内发布。。之前主要考虑到大多数开发者都有获取用户信息的需求。。

**Comment by caidows** [comment]
都没有想好用户怎么实现就改了。。 真是厉害😯

**Comment by jas0ncn** [comment]
我们这个是腾讯云的解决方案，微信的接口调整不是我们负责的哈。

**Comment by fyzhu** [comment]
同问，报错LoginError {type: "ERR_WX_GET_USER_INFO", message: "获取微信用户信息失败，请检查网络状态",
是我本地服务器配置问题，还是微信接口改了导致的

**Comment by fyzhu** [comment]
@wildBanana001 同样的问题，换别人的代码可以了

**Comment by jas0ncn** [comment]
@iterator-zh 这个是写错了，应为 `e.detail`，已经修正。感谢提醒！

**Comment by jas0ncn** [comment]
已经实现，可以参考公告：https://github.com/tencentyun/wafer2-quickstart/issues/10
